### ISSUE TITLE
Problem with overscroll when using BouncingScrollPhysics

### ISSUE THREAD

**Issue by Tobi3030** [andyduke/sync_scroll#1]
There is a problem with `BouncingScrollPhysics`: when you overscroll the ListView and hold it in an overscrolled position the second ListView at first overscrolls like it should, but then jumps back and forth between the overscrolled position and no offset.

You can recreate it using the example code [here](https://pub.dev/packages/sync_scroll). By the way `child:` is missing before `Column` in line 2.

**Comment by andyduke** [comment]
@Tiger3030 
> You can recreate it using the example code here. By the way child: is missing before Column in line 2.

Please explain what you mean.

**Comment by andyduke** [comment]
@Tiger3030 I fixed this problem, but I had to use the deprecated method. With the next Flutter updates this may be broken, I will have to look for another solution, it may take some time.

**Comment by Tobi3030** [comment]
> 
> 
> @Tiger3030
> 
> > You can recreate it using the example code here. By the way child: is missing before Column in line 2.
> 
> Please explain what you mean.

This is what I mean:  34bba3d



> 
> 
> @Tiger3030 I fixed this problem, but I had to use the deprecated method. With the next Flutter updates this may be broken, I will have to look for another solution, it may take some time.

Thank you, now it works as expected.
